name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - linux
          - macos
          - windows

        include:
          - os: ubuntu-latest
            target: linux
            cache: |
              ~/.cache/go-build
              ~/go/pkg/mod
            deps: sudo apt install -y libgl1-mesa-dev
            build: make deploy
            files: ./deploy/linux/*

          - os: macos-latest
            target: macos
            cache: |
              ~/Library/Caches/go-build
              ~/go/pkg/mod
            build: make deploy
            files: ./deploy/darwin/*

          - os: windows-latest
            target: windows
            cache: |
              \AppData\Local\go-build
              ~\go\pkg\mod
            build: go build -v -o firecraft.exe .
            files: ./firecraft.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.cache }}
          key: ${{ matrix.target }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: ${{ matrix.target }}-go-

      - name: Install dependencies
        if: ${{ matrix.deps != null }}
        run: ${{ matrix.deps }}

      - name: Build
        run: ${{ matrix.build }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.target }}
          path: ${{ matrix.files }}
