name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          - linux
          - macos
          - windows

        include:
          - os: ubuntu-latest
            target: linux
            cache: |
              ~/.cache/go-build
              ~/go/pkg/mod
            build: make firecraft
            files: ./firecraft

          - os: macos-latest
            target: macos
            cache: |
              ~/Library/Caches/go-build
              ~/go/pkg/mod
            build: make firecraft
            files: ./firecraft

          - os: windows-latest
            target: windows
            cache: |
              \AppData\Local\go-build
              ~\go\pkg\mod
            build: GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ MSYS2_ARCH=x86_64 go build -v -o firecraft.exe ./bin/firecraft
            files: ./firecraft.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.cache }}
          key: ${{ matrix.target }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: ${{ matrix.target }}-go-

      - name: Build
        run: ${{ matrix.build }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.target }}
          path: ${{ matrix.files }}
